### ISSUE TITLE
Non-hexadecimal number stops the build of Tux

### ISSUE THREAD

**Issue by FAMILIAR-project** [HommeOursPorc/TuxArt#16]
`tuxart --grid linux-4.13.3 42`

```
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/sources/main.py", line 28, in <module>
    main()
  File "/root/.local/lib/python3.7/site-packages/sources/main.py", line 22, in main
    tuxmodifier.tuxcolorizer()
  File "/root/.local/lib/python3.7/site-packages/sources/tuxmodifier.py", line 78, in tuxcolorizer
    shadow = colorengine.shadowcolor(color2)
  File "/root/.local/lib/python3.7/site-packages/sources/colorengine.py", line 68, in shadowcolor
    rgbtriplet = struct.unpack('BBB',bytes.fromhex(rgbstr))
ValueError: non-hexadecimal number found in fromhex() arg at position 7
```

but I think the problem can happen for --gif or -f 
The problem occurs randomly (a grid of 2 elements can fail as well)

**Comment by ark-sys** [comment]
This error seems to be solved, let me know if the problem still persists in the new release
